ticketbooking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from django.urls import path

from . import views
from .views import (CancelView, CreateStripeCheckoutSessionView, SuccessView,
                    details, index, movie)

app_name = "web"

urlpatterns = [
    path("", index.as_view(), name="index"),
    path("details/<int:pk>", details.as_view(), name="details"),
    path("login", views.login_1, name="login"),
    path("success/", SuccessView.as_view(), name="success"),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("movie", movie.as_view(), name="movie"),
    path("seat", views.seat, name="seat"),
    path("signup", views.signup, name="signup"),
    path("success", views.success, name="success"),
    path("sorry", views.sorry, name="sorry"),
    path("logout", views.logout_view, name="logout"),
    path(
        "create-checkout-session/",
        CreateStripeCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
]

web/models.py
from django.db import models

# Create your models here.


class movie_card(models.Model):
    image = models.ImageField(upload_to="media")
    movie_name = models.CharField(max_length=50)
    movie_year = models.DateField()
    movie_quality = models.CharField(max_length=3)
    movie_time = models.CharField(max_length=20)
    movie_rating = models.CharField(max_length=10)
    details = models.CharField(max_length=600)


class movie_content(models.Model):
    image = models.ImageField(upload_to="media")
    title_one = models.CharField(max_length=50)
    title_two = models.CharField(max_length=50)
    head_one = models.CharField(max_length=50)
    content_one = models.CharField(max_length=250)
    head_two = models.CharField(max_length=50)
    content_two = models.CharField(max_length=250)

web/views.py
import stripe
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import DetailView, TemplateView

from .models import movie_card, movie_content

# Create your views here.


class index(TemplateView):
    template_name = "web/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["loop"] = movie_card.objects.all()
        context["code"] = movie_content.objects.all()

        return context


class movie(TemplateView):
    template_name = "web/movie.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["loop"] = movie_card.objects.all()

        return context


class details(DetailView):
    template_name = "web/details.html"

    model = movie_card


def login_1(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("index")
        else:
            return redirect("signup")
    return render(request, "web/account/login.html")


def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")

        if password == confirm_password:
            customer = User.objects.create_user(
                request, username, email, password, confirm_password
            )
            customer.save()

        return redirect("login_1")

    return render(request, "web/account/signup.html")


# def login(request):
#     return render (request, 'web/account/login.html')
# def signup(request):
#     return render(request,'web/account/signup.html')


def success(request):
    return render(request, "web/success.html")


def sorry(request):
    return render(request, "web/sorry.html")


def seat(request):
    return render(request, "web/seat.html")


stripe.api_key = settings.STRIPE_SECRET_KEY


class CreateStripeCheckoutSessionView(View):
    """
    Create a checkout session and redirect the user to Stripe's checkout page
    """

    def post(self, request, *args, **kwargs):
        # price = 220

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[
                {
                    "price_data": {
                        "currency": "INR",
                        "unit_amount": int(250) * 100,
                        "product_data": {"name": "ticket"},
                    },
                    "adjustable_quantity": {
                        "enabled": True,
                        "minimum": 1,
                        "maximum": 10,
                    },
                    "quantity": 1,
                },
            ],
            mode="payment",
            success_url="http://127.0.0.1:8000/",
            cancel_url=settings.PAYMENT_CANCEL_URL,
        )
        return redirect(checkout_session.url)


def logout_view(request):
    logout(request)
    return render(request, "web/index.html")


from django.views.generic import TemplateView


class SuccessView(TemplateView):
    template_name = "web/payment/success.html"


class CancelView(TemplateView):
    template_name = "web/payment/cancel.html"

templates/web/account/login.html
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <link rel="stylesheet" href="{% static "web/css/styles.css" %}" type="text/css" media="all" />

    <link rel="stylesheet" href="{% static "web/css/font-awesome.min.css" %}" type="text/css" media="all">

</head>

<body>
    <div id="block" class="w3lvide-content" data-vide-bg="{% static "web/images/johnwick" %}" data-vide-options="position: 0% 50%">
            <!-- /form -->
            <div class="workinghny-form-grid">
                <div class="main-hotair">
                    <div class="content-wthree">
                        <h1>Login</h1>
                        <form action="#" method="POST">

                            {% csrf_token %}
                            <input type="text" class="text" name="username" placeholder="User Name" required="" autofocus>
                            <input type="password" class="password" name="password" placeholder="Password" required="" autofocus>
                            <button class="btn" type="submit" style="background:hsl(57, 97%, 45%); color:black">Login</button>
                        </form>
           
                        <p class="continue"><span>Or create account <a href="{% url "web:signup" %}">SignUp</a></span></p>
                    </div>
                </div>
       </div>
    </div>
    <!-- //form section start -->
      <!-- js -->
  <script src="{% static "web/js/jquery.min.js" %}"></script>
  <!-- //js -->
  <script src="{% static "web/js/jquery.vide.js" %}"></script>
</body>

</html>
{% endblock  %}

templates/web/account/signup.html
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <link rel="stylesheet" href="{% static "web/css/styles.css" %}" type="text/css" media="all" />

    <link rel="stylesheet" href="{% static "web/css/font-awesome.min.css" %}" type="text/css" media="all">

</head>

<body>
    <div id="block" class="w3lvide-content" data-vide-bg="{% static "web/images/johnwick" %}" data-vide-options="position: 0% 50%">
            <!-- /form -->
            <div class="workinghny-form-grid">
                <div class="main-hotair">
                    <div class="content-wthree">
                        <h1>SignUp</h1>
                        <form action="#" method="POST">
                            {% csrf_token %}
                            <input type="text" class="text" name="username" placeholder="User Name" required autofocus>
                            <input type="email" class="text" name="email" placeholder="Email Address" required autofocus>
                            <input type="password" class="password" name="password" placeholder="Password" required autofocus>
                            <input type="password" class="password" name="confirm_password" placeholder="Confirm Password" required autofocus>
                            <button class="btn" type="submit" style="background:hsl(57, 97%, 45%); color:black"><a href="{% url "web:login" %}" >Join</a></button>
                        </form>
                        <p class="continue"><span>To continue to CinemaTicket <a href="{% url 'web:login' %}">Login</a></span></p>
                    </div>
                </div>
       </div>
    </div>
    <!-- //form section start -->
      <!-- js -->
  <script src="{% static "web/js/jquery.min.js" %}"></script>
  <!-- //js -->
  <script src="{% static "web/js/jquery.vide.js" %}"></script>
</body>

</html>
{% endblock  %}

templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cinema Ticket</title>
  <link rel="stylesheet" href="{% static "web/css/style.css" %}">
  <!-- 
    - google font link
  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>

<body id="top">

 
  {% include 'web\partials\header.html' %}

  {% block content %} 
  
  {% endblock %}
  
  {% include 'web\partials\footer.html' %}
   

  <!-- 
    - custom js link
  -->
  <script src="{% static "web/js/script.js" %}"></script>

  <!-- 
    - ionicon link
  -->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>

templates/web/details.html
{% extends "web/base.html" %}

{% load static %}

{% block content %}

  <main>
    <article>

      <section class="movie-detail">
        <div class="container">

          <figure class="movie-detail-banner">
            <img src="{{object.image.url}}" alt="Movie Image">
          </figure>

          <div class="movie-detail-content">

            <p class="detail-subtitle">Now Ticket Booking</p>

            <h1 class="h1 detail-title">{{object.movie_name}}</h1>

            <div class="meta-wrapper">

              <div class="badge-wrapper">
                <div class="badge badge-fill">PG 13</div>

                <div class="badge badge-outline">{{object.movie_quality}}</div>
              </div>

              <div class="ganre-wrapper">
                <a href="#">Comedy,</a>

                <a href="#">Action,</a>

                <a href="#">Adventure,</a>

                <a href="#">Science Fiction</a>
              </div>

              <div class="date-time">

                <div>
                  <ion-icon name="calendar-outline"></ion-icon>

                  <time datetime="2021">{{object.movie_year}}</time>
                </div>

                <div>
                  <ion-icon name="time-outline"></ion-icon>

                  <time datetime="PT115M">{{object.movie_time}}</time>
                </div>

              </div>

            </div>

            <p class="storyline">
              {{object.details}}
            </p>

            <div class="details-actions">

                <button><a href="{% url "web:seat" %}" style="color:white;">02.30 PM</a></button>
                <button><a href="{% url "web:seat" %}" style="color:white;">06.15 PM</a></button>
                <button><a href="{% url "web:seat" %}" style="color:white;">09.00 PM</a></button>          

            </div>
          </div>

        </div>
      </section>


    </article>
  </main>

{% endblock  %}

templates/web/index.html
{% extends "web/base.html" %}

{% load static %}

{% block content %}


  <main>
    <article>

      <!-- 
        - #HERO
      -->

      <section class="hero">
        <div class="container">

          <div class="hero-content">

            <h1 class="h1 hero-title">
              Our Exclusive <strong>Cinema</strong>,Ticket Booking.
            </h1>

            <div class="meta-wrapper">

              <div class="badge-wrapper">
                <div class="badge badge-fill">PG 18</div>

                <div class="badge badge-outline">HD / 2K</div>
              </div>

              <div class="ganre-wrapper">

                <a href="#">Comedy,</a>

                <a href="#">Drama</a>
              </div>

              <div class="date-time">

                <div>
                  <ion-icon name="calendar-outline"></ion-icon>

                  <time datetime="2022">2024</time>
                </div>

                <div>
                  <ion-icon name="time-outline"></ion-icon>

                  <time datetime="PT128M">128 min</time>
                </div>

              </div>

            </div>

            <button class="btn btn-primary">
              <ion-icon name="play"></ion-icon>

              <span><a href="#upcoming">BOOK NOW</a></span>
            </button>

          </div>

        </div>
      </section>

      <section class="upcoming" id="upcoming">
        <div class="container">

          <div class="flex-wrapper">

            <div class="title-wrapper">
              <p class="section-subtitle">Booking Now</p>

              <h2 class="h2 section-title">Explore Latest Movies</h2>
            </div>

            <ul class="filter-list">

              <li>
                <button class="filter-btn">Movies</button>
              </li>

            </ul>
          </div>
          <ul class="movies-list  has-scrollbar">
            {% for m in loop %}

            <li>
              <div class="movie-card">
                <a href="{% url "web:details" m.id %}">
                  <figure class="card-banner">
                    <img src="{{m.image.url}}" alt="movies Images">
                  </figure>
                </a>

                <div class="title-wrapper">
                  <a href="./movie-details.html">
                    <h3 class="card-title">{{m.movie_name}}</h3>
                  </a>

                  <time datetime="2022">{{m.movie_year}}</time>
                </div>

                <div class="card-meta">
                  <div class="badge badge-outline">{{m.movie_quality}}</div>

                  <div class="duration">
                    <ion-icon name="time-outline"></ion-icon>

                    <time datetime="PT137M">{{m.movie_time}}</time>
                  </div>

                  <div class="rating">
                    <ion-icon name="star"></ion-icon>

                    <data>{{m.movie_rating}}</data>
                  </div>
                </div>
              </div>
            </li>

            {% endfor %}

          </ul>   
        </div>
      </section>


      <section class="service">
        <div class="container">
          {% for c in code %}
        

          <div class="service-banner">
            <figure>  
              <img src="{{c.image.url}}" alt="HD 4k resolution! only $3.99" style="width:400px;">
            </figure>

            <a href="{% static "web/images/cinematicketbooking_image.jpg" %}" download class="service-btn">
              <span>Download</span>

              <ion-icon name="download-outline"></ion-icon>
            </a>
          </div>

          <div class="service-content">

            <p class="service-subtitle">Our Services</p>

            <h2 class="h2 service-title">{{c.title_one}}</h2>

            <p class="service-text">
              {{c.title_two}}
            </p>
            <ul class="service-list">
              
              <li>
                <div class="service-card">
                  <div class="card-icon">
                    <ion-icon name="tv"></ion-icon>
                  </div>
                  <div class="card-content">
                    <h3 class="h3 card-title">{{c.head_one}}</h3>
                    <p class="card-text">
                      {{c.content_one}}
                    </p>
                  </div>
                </div>
              </li>

              <li>
                <div class="service-card">
                  <div class="card-icon">
                    <ion-icon name="videocam"></ion-icon>
                  </div>
                  <div class="card-content">
                    <h3 class="h3 card-title">{{c.head_two}}</h3>
                    <p class="card-text">
                      {{c.content_two}}
                    </p>
                  </div>
                </div>
              </li>

            </ul>

          </div>
          {% endfor %}
        </div>
      </section>



    </article>
  </main>

{% endblock  %}

templates/web/movie.html
{% extends "web/base.html" %}

{% load static %}

{% block content %}

<section class="upcoming" id="upcoming">
  <div class="container">

    <div class="flex-wrapper">

      <div class="title-wrapper">
        <p class="section-subtitle">Booking Now</p>

        <h2 class="h2 section-title">Explore Latest Movies</h2>
      </div>

      <ul class="filter-list">

        <li>
          <button class="filter-btn">Movies</button>
        </li>

      </ul>
    </div>
    <ul class="movies-list  has-scrollbar">
      {% for m in loop %}

      <li>
        <div class="movie-card">
          <a href="{% url "web:details" m.id %}">
            <figure class="card-banner">
              <img src="{{m.image.url}}" alt="movies Images">
            </figure>
          </a>

          <div class="title-wrapper">
            <a href="./movie-details.html">
              <h3 class="card-title">{{m.movie_name}}</h3>
            </a>

            <time datetime="2022">{{m.movie_year}}</time>
          </div>

          <div class="card-meta">
            <div class="badge badge-outline">{{m.movie_quality}}</div>

            <div class="duration">
              <ion-icon name="time-outline"></ion-icon>

              <time datetime="PT137M">{{m.movie_time}}</time>
            </div>

            <div class="rating">
              <ion-icon name="star"></ion-icon>

              <data>{{m.movie_rating}}</data>
            </div>
          </div>
        </div>
      </li>

      {% endfor %}

    </ul>   
  </div>
</section>

{% endblock %}

templates/web/partials/footer.html
{% load static %}

  <!-- 
    - #FOOTER
  -->

  <footer class="footer">

    <div class="footer-top">
      <div class="container">

        <div class="footer-brand-wrapper">

          <a href="./index.html" class="logo">
            <img src="{% static "web/images/logo.png" %}" alt="Filmlane logo" style="width:200px;">
          </a>

          <ul class="footer-list">

            <li>
              <a href="{% url "web:index" %}" class="footer-link">Home</a>
            </li>

            <li>
              <a href="#upcoming" class="footer-link">Movie</a>
            </li>

            <li>
              <a href="#" class="footer-link">TV Show</a>
            </li>

            <li>
              <a href="#" class="footer-link">Web Series</a>
            </li>

            <li>
              <a href="#" class="footer-link">Pricing</a>
            </li>

          </ul>

        </div>

        <div class="divider"></div>

        <div class="quicklink-wrapper">

          <ul class="quicklink-list">

            <li>
              <a href="https://policies.google.com/faq?hl=en-US" class="quicklink-link">Faq</a>
            </li>

            <li>
              <a href="https://support.google.com/" class="quicklink-link">Help center</a>
            </li>

            <li>
              <a href="https://policies.google.com/terms?hl=en-US" class="quicklink-link">Terms of use</a>
            </li>

            <li>
              <a href="https://policies.google.com/privacy?hl=en-US" class="quicklink-link">Privacy</a>
            </li>

          </ul>

          <ul class="social-list">

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-facebook"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li>
              <a href="https://pin.it/64gzCpV" class="social-link">
                <ion-icon name="logo-pinterest"></ion-icon>
              </a>
            </li>

            <li>
              <a href="https://www.linkedin.com/in/sadhik-ali-407544272/" class="social-link">
                <ion-icon name="logo-linkedin"></ion-icon>
              </a>
            </li>

          </ul>

        </div>

      </div>
    </div>

    <div class="footer-bottom">
      <div class="container">

        <p class="copyright">
          &copy; 2024 <a href="#0" target="_blank">Sadhik Ali</a>. All Rights Reserved
        </p>

        <img src="{% static "web/images/footer-bottom-img.png" %}" alt="Online banking companies logo" class="footer-bottom-img">

      </div>
    </div>

  </footer>

  <!-- 
    - #GO TO TOP
  -->

  <a href="#top" class="go-top" data-go-top>
    <ion-icon name="chevron-up"></ion-icon>
  </a>

templates/web/partials/header.html
 {% load static %}
 
 <!-- 
    - #HEADER
  -->

  <header class="header" data-header>
    <div class="container">

      <div class="overlay" data-overlay></div>

      <a href="./index.html" class="logo" style="display: flex;">
        <img src="{% static "web/images/logo.png" %}" alt="Filmlane logo" style="width:200px;">
      </a>


      <div class="header-actions">

        <button class="search-btn">
          <ion-icon name="search-outline"></ion-icon>
        </button>

        <div class="lang-wrapper">
          <label for="language">
            <ion-icon name="globe-outline"></ion-icon>
          </label>

          <select name="language" id="language">
            <option value="en">EN</option>
            <option value="au">AU</option>
            <option value="ar">AR</option>
            <option value="tu">TU</option>
          </select>
        </div>

        {% comment %} <button class="btn btn-primary"><a href="{% url 'web:login' %}">Sign in</a></button> {% endcomment %}
        <button class="btn btn-primary" style="height: 50px;">
          <ul>
            {% if request.user.is_authenticated %}
            <li>
              <a href="{% url 'web:logout' %}" class="nav_a">Logout</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'web:login' %}" class="nav_a" >Login</a>
            </li>
            {% endif %}
          </ul>
        </button>

      </div>

      <button class="menu-open-btn" data-menu-open-btn>
        <ion-icon name="reorder-two"></ion-icon>
      </button>

      <nav class="navbar" data-navbar>

        <div class="navbar-top">

          <a href="./index.html" class="logo">
            <img src="./assets/images/logo.svg" alt="Filmlane logo">
          </a>

          <button class="menu-close-btn" data-menu-close-btn>
            <ion-icon name="close-outline"></ion-icon>
          </button>

        </div>

        <ul class="navbar-list">

          <li>
            <a href="{% url 'web:index' %}" class="navbar-link">Home</a>
          </li>

          <li>
            <a href="{% url 'web:movie' %}" class="navbar-link">Movie</a>
          </li>

          <li>
            <a href="{% url "web:sorry" %}" class="navbar-link">Web Series</a>
          </li>

          {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'auth_logout' %}" class="navbar-link">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'web:login' %}" class="navbar-link" >Login</a>
          </li>
          {% endif %}

        </ul>

        <ul class="navbar-social-list">

          <li>
            <a href="#" class="navbar-social-link">
              <ion-icon name="logo-twitter"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="navbar-social-link">
              <ion-icon name="logo-facebook"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="navbar-social-link">
              <ion-icon name="logo-pinterest"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="navbar-social-link">
              <ion-icon name="logo-instagram"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="navbar-social-link">
              <ion-icon name="logo-youtube"></ion-icon>
            </a>
          </li>

        </ul>

      </nav>

    </div>
  </header>

templates/web/payment/cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="alert alert-info" role="alert">
    Forgot to add something to your cart?
    <a
        href="{% url 'web:product-list' %}"
        >Go to Products</a
      >
  </div>
</body>
</html>

templates/web/payment/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="alert alert-success" role="alert">
    Thanks for purchasing our product
    <a
        href="{% url 'web:product-list' %}"
        >Go to Products</a
      >
  </div>
</body>
</html>

templates/web/seat.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="./images/icon.png" type="image/png" sizes="48x48" />
    <title>Cinema Booking</title>
    <link rel="stylesheet" href="{% static "web/css/seat.css" %}" />
  </head>
  <body>
    <div class="movie-container">    
      <h1>{{object.movie_name}}</h1>
      <select id="movie">
        <option value="200">GOLD</option>
        <option value="200">PLATINUM</option>
      </select>
    </div>

    <ul class="showcase">
      <li>
        <div class="seat"></div>
        <small>N/A</small>
      </li>
      <li>
        <div class="seat selected"></div>
        <small>Selected</small>
      </li>
      <li>
        <div class="seat occupied"></div>
        <small>Occupied</small>
      </li>
    </ul>

    <div id="container" class="container">
      <div id="screen" class="screen"></div>
    </div>
    <p id="text" class="text">You have selected <span id="count">0</span> seats for a price of $<span id="total">0</span></p>
    <div id="buttons" class="buttons displayNone">  
      
      <button class="buy" type="submit"><a href="{% url "web:success" %}">Book Now</a></button>
      <button class="cancel" type="submit">cancel</button>
    </div>
    <script src="{% static "web/js/app.js" %}"></script>
  </body>
</html>

templates/web/sorry.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body style="overflow-y: hidden; overflow-x: hidden;">
  <h4 style="padding: 10px;"><a href="{% url "web:index" %}" style="text-decoration:none;">< Back to Home</a></h4>
  <div style="position: relative; right: 120px;"> 
    
    <center>
      
      <img src="{% static "web/images/sorry.png" %}" alt="" style="width:290px; position: absolute;">
      <h1 style="color:red;">Sorry !!!</h1>
    </center>    
 
  </div>
</body>
</html>